### ISSUE TITLE
세번째 스터디

### ISSUE THREAD

**Issue by SeokHyeonChin** [calvin0627/java-study#8]
5. 클래스 : whiteship/live-study#5
6. 상속: whiteship/live-study#6

**Comment by calvin0627** [comment]
https://github.com/calvin0627/java-study/blob/jb/jb/5.%20%ED%81%B4%EB%9E%98%EC%8A%A4.md
https://github.com/calvin0627/java-study/blob/jb/jb/6.%20%EC%83%81%EC%86%8D.md

**Comment by tkdwns159** [comment]
[https://github.com/calvin0627/java-study/blob/main/Sangjun/java_class.md](url)

**Comment by SeokHyeonChin** [comment]
[](https://github.com/calvin0627/java-study/blob/main/Sangjun/java_class.md)
